services:
  - type: web
    name: rasoiverse
    env: node
    plan: free
    buildCommand: npm install && npm --prefix client install && npm --prefix server install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.15.0
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
